export const GET_LIST_USER_ADMIN = 'GET_LIST_USER_ADMIN';
export const GET_DETAIL_USER_ADMIN = 'GET_DETAIL_USER_ADMIN';
export const CREATE_USER_ADMIN = 'CREATE_USER_ADMIN';
export const EDIT_INFO_USER_ADMIN = 'EDIT_INFO_USER_ADMIN';
export const GET_KIND_OF_USER = 'GET_KIND_OF_USER';