export const GET_INFO_USER = 'GET_INFO_USER';
export const EDIT_INFO_USER = 'EDIT_INFO_USER';
export const GET_LIST_USER_ADMIN = 'GET_LIST_USER_ADMIN';
export const GET_DETAIL_USER_ADMIN = 'GET_DETAIL_USER_ADMIN';